apiVersion: v2
name: loki
description: A Loki chart for Kubernetes
type: application
version: 5.22.0
appVersion: "2.9.1"

dependencies:
- name: loki
  version: 5.22.0
  repository: https://grafana.github.io/helm-charts