jenkins:
  jobs:
    - script: >
        pipelineJob('ClusterEyeDeployment') {
            description('ClusterEye deployment.')
            keepDependencies(false)
            properties {
                disableConcurrentBuildsJobProperty {
                    abortPrevious(false)
                }
            }
            definition {
                cpsScmFlowDefinition {
                    scm {
                        git {
                            configVersion(2)
                            userRemoteConfigs {
                                hudson.plugins.git.UserRemoteConfig {
                                    url('https://github.com/urmas-villem/ClusterEye.git')
                                }
                            }
                            branches {
                                hudson.plugins.git.BranchSpec {
                                    name('*/main')
                                }
                            }
                            doGenerateSubmoduleConfigurations(false)
                            submoduleCfg('[]')
                            extensions('[]')
                        }
                    }
                    scriptPath('Jenkinsfile')
                    lightweight(true)
                }
            }
            triggers {}
            disabled(false)
        }
