apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: checker-sa
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "namespaces", "configmaps"]
    verbs: ["get", "watch", "list"]