apiVersion: v1
kind: ConfigMap
metadata:
  name: clustereye-config
  namespace: default
data:
  prometheus: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/prometheus/prometheus/releases/latest", "|", "jq", "-r", "'.tag_name'"],
      "eolUrl": "https://endoflife.date/api/prometheus.json",
      "note": "",
      "nameexception": ""
    }
  logstash: |
    {
      "command": ["curl", "-s", "https://www.docker.elastic.co/r/logstash/logstash-oss", "|", "grep", "-Eo", "'logstash-oss:[0-9]+\\.[0-9]+\\.[0-9]+'", "|", "sed", "'s/logstash-oss://'", "|", "sort", "-Vr", "|", "head", "-n", "1"],
      "eolUrl": "https://endoflife.date/api/logstash.json",
      "note": "",
      "nameexception": ""
    }
  alertmanager: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/prometheus/alertmanager/releases/latest", "|", "jq", "-r", "'.tag_name'"],
      "eolUrl": "",
      "note": "Alertmanager versions do not have a specific 'end of life'",
      "nameexception": ""
    }
  istiod: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/istio/istio/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "https://endoflife.date/api/istio.json",
      "note": "",
      "nameexception": "discovery"
    }
  blackbox: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/prometheus/blackbox_exporter/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": "blackbox-exporter"
    }
  argocd: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/argoproj/argo-cd/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "https://endoflife.date/api/argo-cd.json",
      "note": "Finding the EOL for this needs some bugfixing - there is some formatting issue here. Ill deal with it later.",
      "nameexception": "server"
    }
  node-exporter: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/prometheus/node_exporter/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  kube-state-metrics: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/kubernetes/kube-state-metrics/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  kiali: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/kiali/kiali/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  filebeat: |
    {
      "command": ["curl", "-s", "https://www.docker.elastic.co/r/beats/filebeat", "|", "grep", "-Eo", "'filebeat:[0-9]+\\.[0-9]+\\.[0-9]+'", "|", "sed", "'s/filebeat://'", "|", "sort", "-Vr", "|", "head", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  sealed-secrets-controller: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/bitnami-labs/sealed-secrets/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  external-dns: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/kubernetes-sigs/external-dns/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  loki: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/grafana/loki/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  mimir: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/grafana/mimir/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sed", "'s/mimir-//'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": "ingester"
    }
  tempo: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/grafana/tempo/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": "ingester"
    }
  jenkins: |
    {
      "command": ["curl", "-s", "https://get.jenkins.io/war-stable/", "|", "awk", "-F'\"'", "'/href=\\\"[0-9]+\\.[0-9]+\\.[0-9]+\\/\\\"/{print $2}'", "|", "sed", "'s/href=//;s/\\///g'", "|", "head", "-1", "|", "sed", "'s/$/-lts/'"],
      "eolUrl": "",
      "note": "",
      "nameexception": ""
    }
  harbor: |
    {
      "command": ["curl", "-s", "https://api.github.com/repos/goharbor/harbor/releases", "|", "jq", "'.[0:20] | map(.tag_name)'", "|", "jq", "-r", "'.[]'", "|", "grep", "-v", "-E", "'beta|rc|alpha'", "|", "sort", "-V", "|", "tail", "-n", "1"],
      "eolUrl": "",
      "note": "",
      "nameexception": "core"
    }
