apiVersion: apps/v1
kind: Deployment
metadata:
  name: jsapp
  labels:
    app: jsapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jsapp
  template:
    metadata:
      labels:
        app: jsapp
    spec:
      serviceAccountName: checker
      containers:
      - name: jsapp
        image: huxlee/jsapp:v1.8.8
        ports:
        - containerPort: 9191
        envFrom:
        - configMapRef:
            name: software-config