apiVersion: apps/v1
kind: Deployment
metadata:
  name: clustereye
  labels:
    app: clustereye
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clustereye
  template:
    metadata:
      labels:
        app: clustereye
    spec:
      serviceAccountName: clustereye
      containers:
      - name: clustereye
        image: huxlee/jsapp:v1.8.8
        ports:
        - containerPort: 9191
        envFrom:
        - configMapRef:
            name: clustereye-config