apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager2
  labels:
    app: alertmanager2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager2
  template:
    metadata:
      labels:
        app: alertmanager2
    spec:
      containers:
      - name: alertmanager
        image: 6256741518459.dkr.ecr.eu-west-1.amazonaws.com/dockerhub/prom/alertmanager@sha256:db8303fa05341f5dc6b19b36a97325cd1b8307254ed9042a2c554af71f3c0284
        ports:
        - containerPort: 9093
